### ISSUE TITLE
Bower.json file doesn't contain a main property

### ISSUE THREAD

**Issue by Pyo25** [Automattic/socket.io-client#835] opened 2015-04-23 11:59 UTC
Hi all,

When we install the library using Bower, the .bower.json file of socket.io-client doesn't contain a [`main` property](http://bower.io/docs/creating-packages/). This property is needed by other tools like [wiredep] (https://github.com/taptapship/wiredep) to work correctly.

For instance, in our app, we use Gulp + Wiredep to automatically inject dependencies when running unit tests. However, the socket library isn't loaded because Wiredep doesn't know which file to load and then our tests fail. 

Thank's !

**Comment by nkzawa** [comment] 2015-04-23 12:37
Duplicate of https://github.com/Automattic/socket.io-client/pull/752
Unfortunately, we don't support Bower officially for now.

**Closed by nkzawa** 2015-04-23 12:37 UTC

**Comment by Pyo25** [comment] 2015-04-30 12:04
Oh ... =/

So for those who are in front of the same problem you could overwrite the main property of a Bower package in your main `bower.json`.

Example:

```
{
  "name": "yourApp",
  "dependencies": {
    "socket.io-client": "~1.3.5"
  },
  "overrides": {
    "socket.io-client": {
      "main": ["socket.io.js"]
    }
  }
}
```
